name: motobox
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.1
  reactive_forms:
  reactive_forms_annotations:
  adaptive_theme: ^3.1.1
  provider: ^6.0.3
  shared_preferences:
  date_format:
  intl:
  flutter_launcher_icons: ^0.10.0
  fluttertoast: ^8.0.9
  cool_dropdown: ^1.4.2
  http: ^0.13.5
  swipeable_tile:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  reactive_forms_generator:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.png
    - assets/brand_logos/BMW.png
    - assets/brand_logos/Ducati.png
    - assets/brand_logos/Harley.png
    - assets/brand_logos/Honda.png
    - assets/brand_logos/Kawazaki.png
    - assets/brand_logos/KTM.png
    - assets/brand_logos/Royal Enfield.png
    - assets/brand_logos/Suzuki.png
    - assets/brand_logos/Triumph.png
    - assets/brand_logos/Yamaha.png
    - assets/bike_models/cbr1000rr-sp.png
    - assets/bike_models/crf1100L.png
    - assets/bike_models/dr650rs.png
    - assets/bike_models/gsrx1000.png
    - assets/bike_models/h2r.png
    - assets/bike_models/hymalayan.png
    - assets/bike_models/hypermotard.png
    - assets/bike_models/interceptor.png
    - assets/bike_models/nine-t.png
    - assets/bike_models/panigale v4r.png
    - assets/bike_models/r1.png
    - assets/bike_models/roadKing.png
    - assets/bike_models/s1000rr.png
    - assets/bike_models/scrambler 900.png
    - assets/bike_models/speed triple rs.png
    - assets/bike_models/sportster883.png
    - assets/bike_models/super adventure.png
    - assets/bike_models/superDuke.png
    - assets/bike_models/t7.png
    - assets/bike_models/z1000.png
    - placeHolder.png
    - assets/invoices/00.png
    - assets/invoices/01.png
    - assets/invoices/02.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    - family: CaviarDreams
      fonts:
        - asset: assets/fonts/CaviarDreams_Bold.ttf
        - asset: assets/fonts/CaviarDreams_BoldItalic.ttf
        - asset: assets/fonts/CaviarDreams_italic.ttf
        - asset: assets/fonts/CaviarDreams.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
